server:
  port: 8002

spring:
  application:
    name: Provider-Payment-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database1
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机模式
      defaultZone: http://eureka1.com:7001/eureka
      #集群模式
      #defaultZone: http://eureka1.com:7001/eureka, http://eureka2.com:7002/eureka

  instance:
    instance-id: Payment-8002
    prefer-ip-address: true