server:
  port: 80

spring:
  application:
    name: Consumer-Order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #单机模式
      #defaultZone: http://eureka1.com:7001/eureka
      #集群模式
      defaultZone: http://eureka1.com:7001/eureka, http://eureka2.com:7002/eureka
