server:
  port: 7001
spring:
  application:
    name: Eureka-Server-1

eureka:
  instance:
    hostname: eureka1.com
  client:
    #此选项代表是否向注册中心注册自己(集群模式下注释此行)
    #register-with-eureka: false
    #此选项表示是否从其他注册中心检索服务(集群模式下注释此行)
    #fetch-registry: false
    #服务中心url
    service-url:
      #d单机模式
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群模式
      #defaultZone: http://eureka2.com:7002/eureka/
